export const types = {
    // auth types
    login: '[auth] login',
    logout: '[auth] logout',
    // ui types
    showLoading: '[ui] showLoading',
    hideLoading: '[ui] hideLoading',
    showItemFormModal: '[ui] showItemFormModal',
    hideItemFormModal: '[ui] hideItemFormModal',
    showTaxFormModal: '[ui] showTaxFormModal',
    hideTaxFormModal: '[ui] hideTaxFormModal',
    loadActive: '[ui] loadActive',
    clearActive: '[ui] clearActive',
    showSidebar: '[ui] showSidebar',
    hideSidebar: '[ui] hideSidebar',
    // balance types
    addBalanceItem: '[balance] addItem',
    deleteBalanceItem: '[balance] deleteItem',
    setBalanceItems: '[balance] setItems',
    updateBalanceItem: '[balance] updateItem',
    setActiveBalanceItem: '[balance] setActiveItem',
    clearActiveBalanceItem: '[balance] clearActiveItem',
    // tax types
    addTaxItem: '[tax] addItem',
    deleteTaxItem: '[tax] deleteItem',
    updateTaxItem: '[tax] updateItem',
    setActiveTaxItem: '[tax] setActiveItem',
    clearActiveTaxItem: '[tax] clearActiveItem'
}